### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by thesmarsch** [htdebeer/meme-collector#5]
Allow user to sort "period" page by the different columns.

**Comment by htdebeer** [comment]
Sorting is now enabled by means of the datatables JavaScript library. 

I still need to add a column per tag to allow sorting on these tags. As a workaround, you can filter a list of memes on a term via the search box in the upper right corner of the table.

**Comment by htdebeer** [comment]
Added a column for each tag. Memes that are tagged with that tag do have a tick mark in that column. You can sort on these columns. With SHIFT+click you can sort on multiple columns!
