### ISSUE TITLE
User Process Flow: selecting, tagging, updating, and advancing through memes

### ISSUE THREAD

**Issue by thesmarsch** [htdebeer/meme-collector#7]
Correct process for selecting, tagging, updating and advancing through memes.
See attached image for explanation of current issues and suggested corrections.
![meme issues_2016 03 09](https://cloud.githubusercontent.com/assets/25108836/23762143/693e32ac-04f5-11e7-8f1f-68c1552125ee.png)

**Comment by htdebeer** [comment]
Did you download the latest version? On my machine it looks like:
![afbeelding](https://cloud.githubusercontent.com/assets/1954802/23762876/c9db6380-04f7-11e7-94cc-b5f4b01d2315.png)

If you select an meme in the list, it opens the meme on the right hand side. I still have to remove the "open" icons. The "superfluous" buttons are from the table plugin to navigate between pages. I agree, they do not make much sense if there is only one page.
