### ISSUE TITLE
Preview window on "period" page has changed with adverse effects

### ISSUE THREAD

**Issue by thesmarsch** [htdebeer/meme-collector#8]
After a git pull today, I now have issues tagging the memes due to a change in the preview window on the "period" page. I opened up the app in two different browser and got two different effects (see images). 
In Chrome [image 1] (which previously worked well), the preview window now comes up blank when memes are selected so tagging is impossible. 
In Firefox [image 2 &3] the screen is no longer a split screen view; rather I must horizontally scroll all the way to the right to find the preview window and when I arrive there the window is about 1/5 the size of the screen (instead of 1/2) making the image very small and causing the tags to take up a lot of space. Previously the set up was working great with a 50/50 split screen and it would be much better to return to that format.
![chrome](https://cloud.githubusercontent.com/assets/25108836/23959522/b57809fe-09a5-11e7-89b1-e225d10e0ad7.png)
![firefox1](https://cloud.githubusercontent.com/assets/25108836/23959523/b578240c-09a5-11e7-8964-e15c62f93708.png)
![firefox2](https://cloud.githubusercontent.com/assets/25108836/23959524/b5788816-09a5-11e7-8de2-e403b0719eae.png)

**Comment by htdebeer** [comment]
After downloading you latest database, it started to look off here as well. So many columns!!!!

Anyway, I've updated the stylesheet and it looks okay again here.
